spring.application.name=interview-simulator
server.port=8080

# MongoDB Atlas
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

# Groq AI
groq.api.keys=${GROQ_API_KEYS}
groq.model=${GROQ_MODEL:llama-3.3-70b-versatile}
groq.api.url=https://api.groq.com/openai/v1/chat/completions

# JWT

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
jwt.expiration-ms=86400000

# CORS
cors.allowed.origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000}

# File Upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Logging
logging.level.com.interview=DEBUG
logging.level.org.springframework.security=WARN


spring.main.allow-bean-definition-overriding=true

# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
